# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI/CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: http://npm/pkg.github.com
          scope: '@chaouredha'

      - name: Install dependencies
        run: npm install

      - name: Run the tests and generate coverage report
        run: npm test -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

      - name: Build production
        run: npm run build-production

      - name: Publish to GitHub packages
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ${{github.repository}} - ${{github.run_number}}
          dockerfile: Dockerfile_server
          password: ${{ secrets.GITHUB_TOKEN }}
          buildArgs: build -t ${{github.repository}} - ${{github.run_number}}
          push: true

      - name: Publish to Docker Hub
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy
        run: npm run deploy

      - name: Updating Domain
        run: echo "Update domain"
